unicommerce_ticket_bkp
newigp_a_b_test_master
newigp_a_b_test_variations
addon_prodtype_mapper
newigp_addons
newigp_override_addons
address_book
address_book_extra_info
address_book_geocode_international
address_book_to_customers
address_final
affiliate
affiliate_template
associate
associate_finance_info
associate_login_details
associate_type
associate_user
brandlist
igp_user_token
igp_users
lockmodules
modules
newigp_associate_extra_info
newigp_entity
newigp_module_pages
newigp_modules
newigp_permissions
newigp_third_party_auth_keys
newigp_webstore
newigp_whitelabel
newigp_whitelabel_panel
source
vendor
vendor_assign_price
vendor_deliveryzone
vendor_extra_info
vendor_general_instructions
vendor_gst_details
vendor_history
vendor_instructions
vendor_penalty
vendor_pincode
vendor_product
base_attr_sets1
newigp_master_attr_sets
newigp_master_attr_vals
AA_barcode_to_components
AA_master_components
AA_vendor_daily_cap
AA_vendor_pincode
AA_vendor_to_components
new_pers_barcode_machine_mapping
newigp_barcodes_set
newigp_baseproduct_machine_type_tmp
blog_cat_map
blog_categories
blog_meta_home
blog_post
blog_post_image
newigp_address_deliverability_check
newigp_address_order_temp_quantity
newigp_address_quantity_temp
newigp_bulk_address_upload_check
newigp_bulk_status_check
newigp_bulk_status_check_tmp
bulk_communication_user_history
cards_collection_ds
cards_hover_mapping
cards_parent_to_child_mapping
cards_strips_order_info
cards_url
cards_url_trash
newigp_card_collection_map
newigp_master_cards_collection
newigp_master_cards_collection_trash
newigp_master_cards_foolterlinks
newigp_master_cards_val
newigp_search_footer
newigp_static_pages
redirects
abandon_cart
cart_lookup
cart_master
newigp_cart_collection
newigp_empty_cart_collection
country_city_top_products
hampers_cat_correction
homepage_banner
homepage_products
homepage_products_subdomain
icons
inpage_banner_user_history
keyword_aliases
n_product_color
n_upsellptp
new_desc
new_filters
new_product_url_info
new_rules_config
newigp_banner
newigp_box_details
newigp_countries_generic_strips
newigp_country_city_strips
newigp_dependency_rp
newigp_dependency_sel_attrs
newigp_featured_product
newigp_festival_bestsellers_info
newigp_filters
newigp_filters_raw
newigp_filters_temp
newigp_footer
newigp_home_page_cards
newigp_inpage_banner_batch
newigp_inpage_banners
newigp_marketing_products
newigp_marketing_products_history
newigp_mm_festivals
newigp_mm_links
newigp_pdp_offers
newigp_prod_design_map
newigp_prod_group
newigp_prod_redirect_pdp
newigp_product_extra_info
newigp_product_extra_info_gst
newigp_product_groups_dec
newigp_product_variant_master
newigp_product_variant_panel
newigp_product_variant_webstore
newigp_product_variants
newigp_products_removed_from_feeds
newigp_products_to_attr_val
newigp_redis_warmup
newigp_rro_fe_codes
newigp_rro_fe_codes_temp
newigp_secondary_navigation
newigp_sku_pers_template_mapping
newigp_solrIndex_product_delimit
newigp_third_party_margins
newigp_thirdparty_products_details
newigp_top_product
newigp_webstore_product_meta
pdp_desc_interlinking
price_range_filter
prod_rank
prod_rank_ab
prod_rank_ds
prod_rank_learning
prod_wh_info
prodcodes
product_cat
product_cat_modified
product_deletion
product_rp
product_rro
product_rrop
product_status_report
product_type_to_product_type
products
products_addon
products_attributes
products_attributes_value
products_candles
products_strip_images
products_theme
products_to_categories
products_to_categories_sitemap
products_vendor
similar_products
cat_fest_url
cat_prod_rank
categories
categories_to_categories
category_bottom
newigp_cat_type_map
newigp_categories_attr_sets
sitemap_category
newigp_category_extra_info
newigp_faq_categories
newigp_faq_questions
newigp_home_page_categories
newigp_home_page_categories_child
rro_menu
rro_menu_temp
rrorules_new
newigp_alkem_doctor
newigp_alkem_image_bkp
newigp_alkem_sales_manager
newigp_microsite_panel_details
newigp_microsite_user_credit_history
newigp_points_upload_cron_data
newigp_points_upload_history
communication_template
communication_template_approved
communication_template_attributes
communication_template_map
communication_template_medium
communication_template_rejected
newigp_communication_panel_template
newigp_communication_panel_template_attr
newigp_email_communication_template_mapper
newigp_master_communicator
newigp_clickpost_account
newigp_clickpost_awb_data
custTimeLine
cust_comment
customer_cat
customer_final
customers_basket
customers_before_cart
customers_firstorder
customers_info
customers_lookup
customers_old_to_new_map
customers_ordersummary
customers_ordersummary_history
customers_product_reco
customers_trans_summary
customers_wishlist
customers_yearwise
customerscart
facebook_user
fb_customers_friends
forgot_pass
newigp_customer_enquirydata
newigp_customer_feedback
newigp_feedback_summary
recommend_to_friend
reconcileCustomers
shortlist_master
user_history_bulk_wallet_credit
user_history_variant_panel
feedback
feedback_customer
loginigp
newigp_user_access_map
newigp_user_access_master
newigp_user_merge_temp
newigp_user_merge_temp_interflora
customers
n_user
dec_barcodemapping
dec_hd_pincodewise
dec_inventory
dec_pincodewise
genericdec_pincodewise
blue_dart_address
bluedart_pincode_validator
bluedart_status
cities
city
city_mapping
countries
country_mapping
country_mobile_prefix
courier
delivery_days
delivery_days_new
fedexPincodes
fedex_international_pincodes
fedex_state_codes
fedex_state_codes_bluedart
firstflight
gpo_int_shipping_slab
gpo_shipping_slab
igp_fedex_invoice_upload
igp_fedex_invoice_upload_bkp
indian_ip
indian_pincodes
inter_track_prod_updation
interflora_country_mapping
interflora_wedding_contactus
ip_to_country
master_pincode_courier
n_state
new_sdd
new_sdd_cut_off_time
new_shipping_slab
newigp_auto_shipped_status_log
newigp_cityid_prodid_offset
newigp_convenience_fee
newigp_courier_shipping_slabs
newigp_delivery_extra_info
newigp_delivery_groups
newigp_express
newigp_master_delivery_groups
newigp_master_product_groups
newigp_master_product_offers_group
newigp_product_groups
newigp_product_pincode_delivery
newigp_master_shipping_groups
newigp_missed_pincodes
newigp_nondeliverable_pincode_redirect
newigp_pincode_offset
newigp_prod_details_for_courier
newigp_product_pincode_redirection
newigp_product_reviews
newigp_product_to_delivery_groups
newigp_redirection_master_product_group
newigp_redirection_product_group
newigp_shipping_groups
newigp_shipping_type_to_slots
newigp_shipping_types
newigp_sku_courier_info
newigp_slot_data_temp
newigp_warehouse_data
newigp_warehouse_list
newigp_warehouse_ops_blacklist_stores
non_bluedart_order
non_bluedart_order_artisan
non_bluedart_order_artisan_international
non_bluedart_order_artisan_marketplace
non_bluedart_order_gai1
non_bluedart_order_gai1_marketplace
pincode
pincodeForMumbai
pincode_backup
newigp_reshipped_history
pincode_delivery_validator
pincode_master
pincodebd
pincodedtdc
pins
scheduler_date
shipping_price_by_country
shipping_price_by_zone
shipping_weight_slabs
state
tax_state_map
tier_one_handels_cost
trackPersonalizeOrders
trackorders
vp_file_upload
zones
coupon_types
coupon_user_history
gift_vouchers
gifts_groupid
newigp_active_coupon_offers
newigp_customerid_voucher_usage
newigp_email_to_gift_vouchers
newigp_gift_voucher_redeem_wallet
newigp_gift_vouchers_extra_info
newigp_type3_voucher_email_usedcount
newigp_voucher_extra_info
voucher
voucher_eligible_customers_email
voucher_newsletter
egv_igp_cards
egv_igp_cards_sud
egv_igp_products_map
egv_loylty_margin
egv_offers_coupon
egv_offers_products_map
egv_order_card_details
egv_qc_category
egv_qc_keys
egv_qc_oauth
egv_qc_product
egv_qc_products_map
egv_vg_products_map
invalid_egv_ids
lr_egv_map_temp
newigp_backup_accounts_balance
newigp_backup_egv_accounts_svc_balance
newigp_bulk_egv_request_details
newigp_egv_accounts_balance
newigp_egv_accounts_balance_logs
newigp_egv_accounts_svc_balance
newigp_egv_buy_now_orders
newigp_egv_mailstatus
newigp_egv_physical_order_input
newigp_egv_physical_order_input_bulk
newigp_egv_physical_order_input_pn
newigp_egv_physical_order_output
newigp_egv_products_details
newigp_egv_products_details_sud
newigp_egv_sku_denom_map
newigp_egv_third_party_alerts
newigp_egv_third_party_logs
newigp_egv_third_party_logs_shivam
newigp_egv_third_party_wallets
newigp_egv_third_party_wallets_shivam
newigp_egv_wallet_discount
newigp_egv_wallet_threshold
newigp_egv_wallet_transaction_history
bounced_list_emails
cancellation_reasons
dnd_block_emails
email_templates
mail_template
mail_transaction
newigp_ald_pepipost_data
newigp_mail_template
newigp_mail_wallet_template
newigp_netcore_sms_templates
newigp_netcore_whatsapp_templates
newigp_sendemail_list
pepipost_data_message_location
pepipost_data_message_media
pepipost_data_message_text
reminder
reminder_coupon_codes
reminder_duration
reminder_occasions
sms_unsubscribe
newigp_feed_customization
newigp_occasion_list_for_feeds
newigp_pla_duplicate_products
component_new_price
corporate_address
handel_order_history
handels_history
handels_pincode_cost
handels_vendor_deliveryBoy
new_vend_ratings
newigp_cfc_courier_map
newigp_handels_dashboard_filter
newigp_handels_vendor_performance_reasons
newigp_handels_vendor_performance_report
newigp_rdc_component_table
newigp_rdc_task_tmp
newigp_vendor_handels_component_order
newigp_vendor_handels_component_order_history
newigp_vendor_transfer_price
barcode_wh_info
product_wh_info
newigp_locus_assigned_user
newigp_locus_batch_config
newigp_locus_batch_summary
newigp_locus_checklist
newigp_locus_checklist_items
newigp_locus_items
newigp_locus_orderid_oproductid_map
newigp_locus_plan
newigp_locus_product_volume
newigp_locus_status
newigp_locus_task
newigp_locus_visits
newigp_lr_bank_address
newigp_lr_sbi_transactions
masqa_media_insta
AP_city_list
AP_pincode_list
AP_prod_list
AP_raw_prod_list
SKU_description
a_seoinfo
aatax
aff_categories
aff_categories_to_categories
aff_count_of_sorting
aff_products_to_categories
aff_relatedproducts
aff_search_keywords
card_occasion_mapping
feed_prodtype
fnc_menu
gci_brands
gci_products
igp_festival_date
image_details
languages
message_templates_user_history
newigp_cron_manager_logging
newigp_master_pallet
newigp_megamenu
newigp_ml_to_db
newigp_press_release_banner
newigp_press_release_banners
newigp_ques_ans
newigp_subscription
newigp_tag_details
newigp_terms_conditions
newigp_xml_template_upload
newigp_youtube_videos
newsletter_subscription
pn
pn_ab
press_release
template_approval
twitter_log
video_pers_del_it
video_title
prep_ticket_index
prep_product_initiate
prep_sku
prep_sku_attribution
prep_product_warehouse
prep_seo
prep_product_categorization
prep_product_attribute
prep_lot
prep_sku_creation
prep_dump
orders
orders_products
order_product_extra_info
orders_extra_info
newigp_orders_product_breakup
newigp_orders_packet_breakup
orders_products_barcodes_info
orders_products_components_info
newigp_webstore_payment_meta
payment_options
communication_attributes_master
communication_templates_master
communication_templates_procedure
templates_attribute_config
newigp_product_pincode_delivery_offset
facility_zone_shelf
facility_shelf_barcode
newigp_vendors
newigp_vendor_account
newigp_vendor_extra_info
newigp_vendor_documents
newigp_vendor_to_barcode
newigp_tour_orders_info
newigp_tour_assembler
locus_order_callback